name: Weekly CBS Pickem Automation

on:
  schedule:
    # Run every Thursday at 8:30 AM PT (15:30 UTC)
    - cron: '30 15 * * 4'
  workflow_dispatch:  # Allow manual triggering
    inputs:
      debug_enabled:
        description: 'Enable debug logging'
        required: false
        default: 'false'
        type: choice
        options:
          - 'true'
          - 'false'

jobs:
  make-picks:
    runs-on: ubuntu-latest
    # Need write permission to push changes back to the repository
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          playwright install chromium

      - name: Set debug mode
        id: set-debug
        run: |
          if [[ "${{ github.event.inputs.debug_enabled }}" == "true" ]]; then
            echo "DEBUG_MODE=--debug" >> $GITHUB_ENV
            echo "Debug mode enabled"
          else
            echo "DEBUG_MODE=" >> $GITHUB_ENV
            echo "Debug mode disabled"
          fi

      - name: Login to CBS Sports
        run: |
          echo "Starting login process..."
          python login.py --headless $DEBUG_MODE
          echo "Login process completed"
        env:
          CBS_USERNAME: "${{ secrets.CBS_USERNAME }}"
          CBS_PASSWORD: "${{ secrets.CBS_PASSWORD }}"
          CBS_POOL_URL: "${{ secrets.CBS_POOL_URL }}"

      - name: Read matchups
        run: |
          echo "Starting matchup reading process..."
          python read_matchups.py $DEBUG_MODE
          echo "Matchup reading completed"
          ls -la */*/matchups.json || echo "No matchups.json found"
        env:
          CBS_USERNAME: "${{ secrets.CBS_USERNAME }}"
          CBS_PASSWORD: "${{ secrets.CBS_PASSWORD }}"
          CBS_POOL_URL: "${{ secrets.CBS_POOL_URL }}"
        
      - name: Predict winners
        run: |
          echo "Starting winner prediction process..."
          # Get the current season and week folder
          SEASON_WEEK=$(ls -td 20*/* | head -n 1)
          echo "Using season/week folder: $SEASON_WEEK"
          python predict_winners.py "$SEASON_WEEK/matchups.json" $DEBUG_MODE
          echo "Winner prediction completed"
          ls -la "$SEASON_WEEK/my_picks.json" || echo "No my_picks.json found"
        
      - name: Make picks
        run: |
          echo "Starting pick submission process..."
          # Get the current season and week folder
          SEASON_WEEK=$(ls -td 20*/* | head -n 1)
          echo "Using season/week folder: $SEASON_WEEK"
          python make_picks.py "$SEASON_WEEK/my_picks.json" $DEBUG_MODE
          echo "Pick submission completed"
        env:
          CBS_USERNAME: "${{ secrets.CBS_USERNAME }}"
          CBS_PASSWORD: "${{ secrets.CBS_PASSWORD }}"
          CBS_POOL_URL: "${{ secrets.CBS_POOL_URL }}"
        
      - name: Generate social previews
        run: |
          echo "Starting social preview generation..."
          # Get the current season and week folder
          SEASON_WEEK=$(ls -td 20*/* | head -n 1)
          echo "Using season/week folder: $SEASON_WEEK"
          python generate_social_previews.py "$SEASON_WEEK" $DEBUG_MODE
          echo "Social preview generation completed"
          ls -la "$SEASON_WEEK/my_picks_1.png" "$SEASON_WEEK/my_picks_2.png" || echo "Preview images not found"
        
      # Upload artifacts as a backup (using v4 of the action)
      - name: Upload social preview images as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: social-previews
          path: |
            **/my_picks_1.png
            **/my_picks_2.png
          retention-days: 7
          
      # Configure Git for committing changes
      - name: Configure Git
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          
      # Commit and push the generated files
      - name: Commit and push generated files
        run: |
          # Get the current season and week folder
          SEASON_WEEK=$(ls -td 20*/* | head -n 1)
          echo "Committing files from: $SEASON_WEEK"
          
          # Check if there are any changes to commit
          git add "$SEASON_WEEK/matchups.json" "$SEASON_WEEK/my_picks.json" "$SEASON_WEEK/my_picks_1.png" "$SEASON_WEEK/my_picks_2.png"
          
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            # Get the current date for the commit message
            CURRENT_DATE=$(date +"%Y-%m-%d")
            git commit -m "Auto-update picks for $SEASON_WEEK on $CURRENT_DATE"
            git push
            echo "Successfully committed and pushed changes"
          fi
